name: Bangumi Plugin CI

on:
  push:
    branches-ignore:
      - release
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Restore, Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Restore NuGet Packages
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --configuration Release --no-build Jellyfin.Plugin.Bangumi.Test
